apiVersion: v1 # Kubernetes API version
kind: Pod # we describe a module(pod)
metadata:
  name: kubia-manual # module name
spec:
  containers:
    - image: luksa/kubia
      name: kubia
      ports:
        - containerPort: 8080 # listening port
          protocol: TCP